openapi: "3.0.0"
info:
  title: Example booking API
  version: 2.0.0
paths:
  /test:
    get:
      operationId: test
      summary: Test endpoint
      responses:
        '200':
          description: Test response
